Repository GoRoutes/GoRoutes_FrontEnd, pull requests merged in 2025-09, with the labels that each got.

#44 Chore 43
  src/components/auth/login/LoginComp.vue
  src/components/auth/register/FormCompOne.vue
  src/components/auth/register/FormCompTwo.vue
  src/components/auth/register/RegisterComp.vue
  src/components/global/InputComp.vue
  src/components/index.js
  src/views/responsibles/MyDependentsView.vue
Labels: Fix, Feat

#53 FEAT: fix of inputs on login screen [REFS: #52]
  src/components/auth/login/LoginComp.vue
  src/components/global/InputComp.vue
Labels: Fix

#59 FEAT: Adiciona suporte para upload de fotos de veículos e atualiza a …
  src/components/admin/vehicles/VehicleRetrieveDataComp.vue
  src/components/global/profiles-images/UploadPhoto.vue
  src/services/admin/vehicles.js
  src/stores/admin/vehicles.js
Labels: Feat

#61 FEAT: fix margins, size of components and position of actions on vehi…
  src/components/admin/route/init/InitRouteComp.vue
  src/components/admin/vehicles/TableVehicles.vue
Labels: Feat
